//go:build windows

package trigger

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateExternalConfig writes an AutoHotkey script for Windows.
func GenerateExternalConfig(hotkeys map[string]string, binary string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	ahkFile := filepath.Join(home, "prompt-agent-hotkeys.ahk")

	var sb strings.Builder
	sb.WriteString("; Generated by prompt-agent daemon setup\n")
	sb.WriteString("; Requires AutoHotkey v2: https://www.autohotkey.com/\n\n")

	for hotkeyStr, promptID := range hotkeys {
		ahk, err := toAHKSyntax(hotkeyStr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ⚠ skipping %q: %v\n", hotkeyStr, err)
			continue
		}
		sb.WriteString(fmt.Sprintf("%s::\n", ahk))
		sb.WriteString(fmt.Sprintf(`  Run 'cmd.exe /k "%s run %s"'`, binary, promptID))
		sb.WriteString("\nreturn\n\n")
	}

	if err := os.WriteFile(ahkFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", ahkFile, err)
	}

	fmt.Printf("✓ Written to %s\n\n", ahkFile)
	fmt.Println("Next steps:")
	fmt.Println("  1. Install AutoHotkey: https://www.autohotkey.com/")
	fmt.Println("  2. Double-click the .ahk file to activate hotkeys")
	fmt.Println("  3. To auto-start: place shortcut in shell:startup folder")
	return nil
}

func toAHKSyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	if len(parts) < 2 {
		return "", fmt.Errorf("need at least modifier+key")
	}

	modMap := map[string]string{
		"ctrl": "^", "control": "^",
		"alt": "!", "option": "!",
		"shift": "+",
		"cmd": "#", "super": "#", "win": "#",
	}

	var mods string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		mods += m
	}

	key := parts[len(parts)-1]
	if key == "space" {
		key = "Space"
	}

	return mods + key, nil
}
