//go:build linux

package trigger

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateExternalConfig writes ~/.xbindkeysrc for use with xbindkeys.
func GenerateExternalConfig(hotkeys map[string]string, binary string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	rcFile := filepath.Join(home, ".xbindkeysrc")

	var sb strings.Builder
	sb.WriteString("# Generated by prompt-agent daemon setup\n")
	sb.WriteString("# Install xbindkeys: sudo apt install xbindkeys\n\n")

	for hotkeyStr, promptID := range hotkeys {
		xbk, err := toXbindkeysSyntax(hotkeyStr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ⚠ skipping %q: %v\n", hotkeyStr, err)
			continue
		}
		// Open a terminal and run prompt-agent
		cmd := fmt.Sprintf(`xterm -e "%s run %s"`, binary, promptID)
		sb.WriteString(fmt.Sprintf("%q\n  %s\n\n", cmd, xbk))
	}

	if err := os.WriteFile(rcFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", rcFile, err)
	}

	fmt.Printf("✓ Written to %s\n\n", rcFile)
	fmt.Println("Next steps:")
	fmt.Println("  1. Install xbindkeys:  sudo apt install xbindkeys")
	fmt.Println("  2. Reload config:      xbindkeys --poll-rc")
	fmt.Println("  3. Or restart:         pkill xbindkeys && xbindkeys")
	return nil
}

func toXbindkeysSyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	if len(parts) < 2 {
		return "", fmt.Errorf("need at least modifier+key")
	}

	modMap := map[string]string{
		"ctrl": "Control", "control": "Control",
		"alt": "Mod1", "option": "Mod1",
		"shift": "Shift",
		"cmd": "Mod4", "super": "Mod4",
	}

	var mods []string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		mods = append(mods, m)
	}

	key := strings.ToUpper(parts[len(parts)-1][:1]) + parts[len(parts)-1][1:]
	return strings.Join(append(mods, key), "+"), nil
}
