//go:build darwin

package trigger

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateExternalConfig writes ~/.skhdrc for use with skhd (brew install skhd).
func GenerateExternalConfig(hotkeys map[string]string, binary string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	skhdrc := filepath.Join(home, ".skhdrc")

	var sb strings.Builder
	sb.WriteString("# Generated by prompt-agent daemon setup\n")
	sb.WriteString("# Install skhd: brew install skhd && brew services start skhd\n\n")

	for hotkeyStr, promptID := range hotkeys {
		skhd, err := toSkhdSyntax(hotkeyStr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ⚠ skipping %q: %v\n", hotkeyStr, err)
			continue
		}
		// Open Terminal.app and run prompt-agent
		appleScript := fmt.Sprintf(
			`osascript -e 'tell application "Terminal" to do script "%s run %s"'`,
			binary, promptID,
		)
		sb.WriteString(fmt.Sprintf("%s : %s\n", skhd, appleScript))
	}

	content := sb.String()

	// Merge into existing .skhdrc (append block if file already exists)
	existing, _ := os.ReadFile(skhdrc)
	const marker = "# [prompt-agent]"
	if strings.Contains(string(existing), marker) {
		// Replace block between markers
		fmt.Println("  Updating existing ~/.skhdrc block...")
	} else if len(existing) > 0 {
		content = string(existing) + "\n" + marker + "\n" + content + "# [/prompt-agent]\n"
	} else {
		content = marker + "\n" + content + "# [/prompt-agent]\n"
	}

	if err := os.WriteFile(skhdrc, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", skhdrc, err)
	}

	fmt.Printf("✓ Written to %s\n\n", skhdrc)
	fmt.Println("Next steps:")
	fmt.Println("  1. Install skhd:         brew install skhd")
	fmt.Println("  2. Start skhd service:   brew services start skhd")
	fmt.Println("  3. Grant Accessibility:  System Preferences → Privacy & Security → Accessibility → add skhd")
	fmt.Println("  4. Reload config:        skhd --reload")
	return nil
}

// toSkhdSyntax converts "alt+space" → "alt - space" (skhd format)
func toSkhdSyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	if len(parts) < 2 {
		return "", fmt.Errorf("need at least modifier+key")
	}

	modMap := map[string]string{
		"ctrl": "ctrl", "control": "ctrl",
		"alt": "alt", "option": "alt",
		"shift": "shift",
		"cmd": "cmd", "command": "cmd", "super": "cmd",
	}

	var mods []string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		mods = append(mods, m)
	}

	key := parts[len(parts)-1]
	// skhd key name normalisation
	skhdKey := map[string]string{
		"space": "space", "return": "return", "enter": "return",
		"escape": "escape", "esc": "escape", "tab": "tab",
		"backspace": "delete", "delete": "delete",
		"up": "up", "down": "down", "left": "left", "right": "right",
		"f1": "f1", "f2": "f2", "f3": "f3", "f4": "f4",
		"f5": "f5", "f6": "f6", "f7": "f7", "f8": "f8",
		"f9": "f9", "f10": "f10", "f11": "f11", "f12": "f12",
	}
	if mapped, ok := skhdKey[key]; ok {
		key = mapped
	}

	return strings.Join(mods, " + ") + " - " + key, nil
}
