//go:build linux

package trigger

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// GenerateExternalConfig writes ~/.xbindkeysrc and outputs snippets for WMs/Compositors.
func GenerateExternalConfig(hotkeys map[string]string, binary string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot find home directory: %w", err)
	}

	rcFile := filepath.Join(home, ".xbindkeysrc")

	// Detect Wayland session
	sessionType := os.Getenv("XDG_SESSION_TYPE")
	waylandDisplay := os.Getenv("WAYLAND_DISPLAY")
	isWayland := strings.ToLower(sessionType) == "wayland" || waylandDisplay != ""

	// Detect Arch Linux
	isArch := false
	if _, err := os.Stat("/etc/arch-release"); err == nil {
		isArch = true
	} else if data, err := os.ReadFile("/etc/os-release"); err == nil {
		isArch = strings.Contains(strings.ToLower(string(data)), "arch")
	}

	var sb strings.Builder
	sb.WriteString("# Generated by prompt-agent daemon setup\n")
	if isArch {
		sb.WriteString("# Install xbindkeys: sudo pacman -S xbindkeys\n\n")
	} else {
		sb.WriteString("# Install xbindkeys: sudo apt install xbindkeys (Debian/Ubuntu) or pacman -S xbindkeys (Arch)\n\n")
	}

	for hotkeyStr, promptID := range hotkeys {
		xbk, err := toXbindkeysSyntax(hotkeyStr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  ⚠ skipping %q: %v\n", hotkeyStr, err)
			continue
		}
		// Find a suitable terminal command to run and hold the output open
		cmd := findTerminalCommand(binary, promptID)
		sb.WriteString(fmt.Sprintf("%q\n  %s\n\n", cmd, xbk))
	}

	if err := os.WriteFile(rcFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", rcFile, err)
	}

	fmt.Printf("✓ Written to %s\n\n", rcFile)

	// Display configurations for WMs/Compositors (crucial for Arch Linux users)
	fmt.Println("======================================================================")
	fmt.Println("⚙️  HOTKEY CONFIGURATION FOR ARCH LINUX / WINDOW MANAGERS / COMPOSITORS")
	fmt.Println("======================================================================")
	fmt.Println("Since you are using Arch Linux, you can configure your hotkeys by adding")
	fmt.Println("one of the following snippets directly to your configuration file:")
	fmt.Println()

	// 1. Hyprland configuration
	fmt.Println("── 1. Hyprland (~/.config/hypr/hyprland.conf) ────────────────────────")
	fmt.Println("# Toggle the GUI Overlay window:")
	fmt.Println("bind = ALT, space, exec, promptly")
	fmt.Println("# Run specific headless recipes:")
	for hotkeyStr, promptID := range hotkeys {
		hMods, hKey := toHyprlandSyntax(hotkeyStr)
		cmd := findTerminalCommand(binary, promptID)
		if hMods != "" {
			fmt.Printf("bind = %s, %s, exec, %s\n", hMods, hKey, cmd)
		} else {
			fmt.Printf("bind = , %s, exec, %s\n", hKey, cmd)
		}
	}
	fmt.Println()

	// 2. Sway / i3 configuration
	fmt.Println("── 2. Sway (~/.config/sway/config) or i3 (~/.config/i3/config) ───────")
	fmt.Println("# Toggle the GUI Overlay window:")
	fmt.Println("bindsym Mod1+space exec promptly")
	fmt.Println("# Run specific headless recipes:")
	for hotkeyStr, promptID := range hotkeys {
		swayKey, err := toSwaySyntax(hotkeyStr)
		if err == nil {
			cmd := findTerminalCommand(binary, promptID)
			fmt.Printf("bindsym %s exec %s\n", swayKey, cmd)
		}
	}
	fmt.Println()

	// 3. sxhkd configuration (Common for dwm/AwesomeWM/i3/bspwm)
	fmt.Println("── 3. sxhkd (~/.config/sxhkd/sxhkdrc) ────────────────────────────────")
	fmt.Println("# Toggle the GUI Overlay window:")
	fmt.Println("alt + space")
	fmt.Println("    promptly")
	fmt.Println("# Run specific headless recipes:")
	for hotkeyStr, promptID := range hotkeys {
		sxhkdKey, err := toSxhdSyntax(hotkeyStr)
		if err == nil {
			cmd := findTerminalCommand(binary, promptID)
			fmt.Printf("%s\n    %s\n", sxhkdKey, cmd)
		}
	}
	fmt.Println()

	// 4. xbindkeys instructions
	fmt.Println("── 4. xbindkeys (~/.xbindkeysrc) ─────────────────────────────────────")
	if isWayland {
		fmt.Println("⚠️  Note: You are in a Wayland session. xbindkeys will NOT work under Wayland.")
		fmt.Println("   Please use the Hyprland, Sway, or sxhkd configs above.")
	} else {
		fmt.Println("xbindkeys configuration has been automatically written to ~/.xbindkeysrc.")
		fmt.Println("To run it:")
		if isArch {
			fmt.Println("  1. Install:  sudo pacman -S xbindkeys")
		} else {
			fmt.Println("  1. Install:  sudo apt install xbindkeys")
		}
		fmt.Println("  2. Start:    xbindkeys")
		fmt.Println("  3. Reload:   xbindkeys --poll-rc")
	}
	fmt.Println("======================================================================")

	return nil
}

func findTerminalCommand(binary, promptID string) string {
	terminals := []struct {
		name     string
		template string
	}{
		{"alacritty", `alacritty --hold -e %s run %s`},
		{"kitty", `kitty --hold %s run %s`},
		{"konsole", `konsole --noclose -e %s run %s`},
		{"xfce4-terminal", `xfce4-terminal --hold -e "%s run %s"`},
		{"gnome-terminal", `gnome-terminal -- bash -c "%s run %s; exec bash"`},
		{"xterm", `xterm -hold -e "%s run %s"`},
	}

	for _, t := range terminals {
		if _, err := exec.LookPath(t.name); err == nil {
			return fmt.Sprintf(t.template, binary, promptID)
		}
	}
	return fmt.Sprintf(`xterm -hold -e "%s run %s"`, binary, promptID)
}

func toXbindkeysSyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	if len(parts) < 2 {
		return "", fmt.Errorf("need at least modifier+key")
	}

	modMap := map[string]string{
		"ctrl": "Control", "control": "Control",
		"alt": "Mod1", "option": "Mod1",
		"shift": "Shift",
		"cmd": "Mod4", "super": "Mod4",
	}

	var mods []string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		mods = append(mods, m)
	}

	key := strings.ToUpper(parts[len(parts)-1][:1]) + parts[len(parts)-1][1:]
	return strings.Join(append(mods, key), "+"), nil
}

func toHyprlandSyntax(s string) (string, string) {
	parts := strings.Split(strings.ToLower(s), "+")
	modMap := map[string]string{
		"ctrl": "CTRL", "control": "CTRL",
		"alt": "ALT", "option": "ALT",
		"shift": "SHIFT",
		"cmd": "SUPER", "super": "SUPER",
	}
	var mods []string
	for _, p := range parts[:len(parts)-1] {
		if m, ok := modMap[p]; ok {
			mods = append(mods, m)
		}
	}
	key := parts[len(parts)-1]
	return strings.Join(mods, " "), key
}

func toSwaySyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	modMap := map[string]string{
		"ctrl": "Control", "control": "Control",
		"alt": "Mod1", "option": "Mod1",
		"shift": "Shift",
		"cmd": "Mod4", "super": "Mod4",
	}
	var res []string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		res = append(res, m)
	}
	key := parts[len(parts)-1]
	return strings.Join(append(res, key), "+"), nil
}

func toSxhdSyntax(s string) (string, error) {
	parts := strings.Split(strings.ToLower(s), "+")
	modMap := map[string]string{
		"ctrl": "ctrl", "control": "ctrl",
		"alt": "alt", "option": "alt",
		"shift": "shift",
		"cmd": "super", "super": "super",
	}
	var res []string
	for _, p := range parts[:len(parts)-1] {
		m, ok := modMap[p]
		if !ok {
			return "", fmt.Errorf("unknown modifier %q", p)
		}
		res = append(res, m)
	}
	key := parts[len(parts)-1]
	return strings.Join(append(res, key), " + "), nil
}
