package demomock
package main

import (
	"context"




























































































































}	fmt.Println("✅ Response complete (5 lines of code)")	fmt.Println("─────────────────────────────────────")	fmt.Println()	fmt.Println("}")	fmt.Println("    fmt.Println(\"Hello, World!\")")	fmt.Println("func main() {")	fmt.Println()	fmt.Println("import \"fmt\"")	fmt.Println()	fmt.Println("package main")	fmt.Println()	fmt.Println("📤 Response (streaming):")	defer server.Close()	}))}`)  ]    }      }        ]          }            "text": "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, World!\")\n}"          {        "parts": [      "content": {    {  "candidates": [		fmt.Fprintf(w, `{		w.Header().Set("Content-Type", "application/json")	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	fmt.Printf("💬 Prompt: Write a simple Hello World in Go\n\n")	fmt.Println("─────────────────────────────────────")	fmt.Println("📝 Demo: Code Generation (Streaming)")	fmt.Println()func runStreamDemo() {}	fmt.Println("   ./demo  (requires available quota)")	fmt.Println("💡 To use with real API, set GEMINI_API_KEY and run:")	fmt.Println()	fmt.Println("✅ Mock demo complete!")	fmt.Println("=====================================")	fmt.Println()	runStreamDemo()	// Demo 2: Show the actual stream test	fmt.Println()	fmt.Println("✅ Response complete")	fmt.Println("─────────────────────────────────────")	fmt.Println()	fmt.Println("language translation.")	fmt.Println("These tasks include visual perception, speech recognition, decision-making, and")	fmt.Println("systems capable of performing tasks that typically require human intelligence.")	fmt.Println("Artificial Intelligence (AI) is a branch of computer science that aims to create")	fmt.Println()	fmt.Println("📤 Response (from mock server):")	fmt.Printf("💬 Prompt: What is Artificial Intelligence?\n\n")	fmt.Println("─────────────────────────────────────")	fmt.Println("📝 Demo: Explain AI (Mock Response)")	// Demo 1: Simple response	fmt.Printf("✅ Client created: %s\n\n", client.Name())	client := gemini.NewClient("mock-key", "gemini-2.5-flash-lite", 30*time.Second)	// Create client with mock server URL	defer mockServer.Close()	}))}`)  ]    }      }        ]          }            "text": "Artificial Intelligence (AI) is a branch of computer science that aims to create systems capable of performing tasks that typically require human intelligence. These tasks include visual perception, speech recognition, decision-making, and language translation."          {        "parts": [      "content": {    {  "candidates": [		fmt.Fprintf(w, `{		w.Header().Set("Content-Type", "application/json")		}			},				},					},						},							{Text: "Artificial Intelligence (AI) is a branch of computer science that aims to create systems capable of performing tasks that typically require human intelligence. These tasks include visual perception, speech recognition, decision-making, and language translation."},						}{							Text string `json:"text"`						Parts: []struct {					}{						} `json:"parts"`							Text string `json:"text"`						Parts []struct {					Content: struct {				{			}{				} `json:"content"`					} `json:"parts"`						Text string `json:"text"`					Parts []struct {				Content struct {			Candidates: []struct {		response := gemini.GenerateContentResponse{	mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {	// Create mock server	fmt.Println()	fmt.Println("=====================================")	fmt.Println("🚀 Gemini API Mock Demo")func main() {)	"github.com/sl/prompt-builder-agent/internal/llm/gemini"	"github.com/sl/prompt-builder-agent/internal/llm"	"time"	"net/http/httptest"	"net/http"	"fmt"